import React from "react";
import Head from "next/head";
import { RecentPostPageStyled } from "./styled";
import Navbar from "@/components/Navbar/Navbar";
import Headbar from "@/components/HeadBar/Headbar";
import FooterWidget from "@/widgets/FooterWidget";
import { SecRecentPostsWidget } from "@/widgets";
import navData from "../../utils/nav.json";

const RecentPostPage = () => {
  return (
    <>
      {" "}
      <Head>
        <title>Web Event</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
        <link
          href="https://fonts.googleapis.com/css2?family=Kanit:wght@300;400;500;600;700&display=swap"
          rel="stylesheet"
        />
      </Head>
      <RecentPostPageStyled>
        <Headbar />
        <Navbar data={navData} />
        <div className="body_container_layout">
          <SecRecentPostsWidget showPagination card={9} />
        </div>
        <div className="footer_layout">
          <FooterWidget />
        </div>
      </RecentPostPageStyled>
    </>
  );
};

export default RecentPostPage;
