import Head from "next/head";
import { HomeStyled } from "../pageStyles/HomeStyled";
import { SecHomeWidget, SecAboutWidget, SecRecentPostsWidget } from "@/widgets";
import Navbar from "@/components/Navbar/Navbar";
import Headbar from "@/components/HeadBar/Headbar";
import FooterWidget from "@/widgets/FooterWidget";
import SecRecentBlogWidget from "@/widgets/SecRecentBlogWidget";
import navData from "../utils/nav.json";

export default function Home() {
  return (
    <>
      <Head>
        <title>Web Event</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
        <link
          href="https://fonts.googleapis.com/css2?family=Kanit:wght@300;400;500;600;700&display=swap"
          rel="stylesheet"
        />
      </Head>
      <HomeStyled>
        <Headbar />
        <Navbar data={navData} />
        <div className="body_container_layout">
          <SecHomeWidget />
          <SecRecentPostsWidget showSeeMore card={3} />
          <SecRecentBlogWidget showSeeMore card={3} />
          <SecAboutWidget />
        </div>
        <FooterWidget />
      </HomeStyled>
    </>
  );
}
